#!/usr/bin/env bash

if [[ "$1" == "" ]]; then
  echo "You must enter an expression"
fi

found=0
while read line
do
  if [[ $found -eq 0 ]]; then
    echo $line | grep -E "$*" > /dev/null
    if [[ $? -eq 0 ]]; then
      exit 0
    fi
    echo $line
  fi
done < "/dev/stdin"
