#!/usr/bin/env bash

if [[ "$1" == "" ]]; then
  while read line
  do
    words=($(echo $line | tr "\t" " " | tr -s " "))
    output=''
    for index in "${!words[@]}"
    do
      output="$output [$(( $index + 1 ))]${words[$index]}"
    done
    echo $output
  done < "/dev/stdin"
  exit 0
fi

if [[ "$1" == "-d" ]]; then
  while read line
  do
    words=($(echo $line | tr "\t" " " | tr -s " "))
    output=''
    for index in "${!words[@]}"
    do
      flag=0
      for input in ${@:2}
      do
        if [[ "$input" -eq "$(( $index + 1 ))" ]] ; then
          flag=1
          break
        fi
      done
      if [[ "$flag" == 0 ]] ; then
        output="$output ${words[$index]}"
      fi
    done
    echo $output
  done < "/dev/stdin"
  exit 0
fi

while read line
do
  words=($(echo $line | tr "\t" " " | tr -s " "))
  output=''
  for index in $@
  do
    output="$output ${words[$(( $index - 1 ))]}"
  done
  echo $output
done < "/dev/stdin"
