#!/usr/bin/env bash

if [[ "$1" == "" ]]; then
  >&2 echo "wordn: You must enter a number"
  exit -1;
fi

while read line
do
  words=($(echo $line | tr "\t" " " | tr -s " "))
  output=''
  for index in $@
  do
    output="$output ${words[$(( $index - 1 ))]}"
  done
  echo $output
done < "/dev/stdin"
